(function(){var s=document.currentScript||document.getElementsByTagName("script")[document.getElementsByTagName("script").length-1],u=s&&s.src?s.src:"",b=u.substring(0,u.lastIndexOf("/")+1),l=document.createElement("link");if(b&&!document.getElementById("cfle-events-css")){l.id="cfle-events-css";l.rel="stylesheet";l.type="text/css";l.href=b+"events.css?v=2";(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(l)}})();
(function(){
var src="/templates/events.htm",all=[],active="all",CACHE_KEY="cfleEventsV2",CACHE_MS=600000,$=function(s,p){return(p||document).querySelector(s)},$$=function(s,p){return(p||document).querySelectorAll(s)};
function tx(v){return String(v||"").replace(/\u00a0/g," ").replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")}
function abs(u){if(!u)return"";var a=document.createElement("a");a.href=u;return a.href}
function el(t,c,x){var e=document.createElement(t);if(c)e.className=c;if(x!==undefined)e.appendChild(document.createTextNode(x));return e}
function dateEl(i){var p=i&&i.parentElement;return p?p.querySelector(".date_stamp .date"):null}
function getDate(v){var m=tx(v).match(/(Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Shabbat|Saturday)\s*,?\s*(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2})\s*,?\s*(\d{4})/i);return m?{weekday:m[1],month:m[2],day:m[3],year:m[4],full:m[1]+", "+m[2]+" "+m[3]+", "+m[4]}:null}
function time(i){var o=i.querySelector(".event_options.list_info"),d,j,x;if(!o)return"";d=o.getElementsByTagName("div");for(j=d.length-1;j>=0;j--){x=tx(d[j].textContent||d[j].innerText);if(/\d{1,2}:\d{2}\s*(am|pm)/i.test(x))return x}return""}
function title(i){var w=i.querySelector(".event_wrapper"),n=w&&w.querySelector(".event_name");return n?tx(n.textContent||n.innerText):""}
function loc(i){var a=i.querySelector('.event_info a[href*="maps.google.com"],.event_info a[href*="google.com/maps"]'),c,b,j,x,p;if(!a)return{text:"",name:"",address:"",url:""};c=a.cloneNode(true);b=c.getElementsByTagName("br");for(j=b.length-1;j>=0;j--)b[j].parentNode.replaceChild(document.createTextNode(" | "),b[j]);x=tx(c.textContent||c.innerText);p=x.split("|");return{text:x.replace(/\s*\|\s*/g," — "),name:tx(p[0]),address:tx(p.slice(1).join(" ")),url:abs(a.getAttribute("href"))}}
function link(i,s){var a=i.querySelector(s);return a?abs(a.getAttribute("href")):""}
function parse(i){var d=dateEl(i),dt,t,l;if(!d)return null;dt=getDate(d.textContent||d.innerText);t=title(i);l=loc(i);return dt&&t?{title:t,date:dt,time:time(i),location:l,detailsUrl:link(i,".more_info a")}:null}
function norm(t){return tx(t).toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/^\s+|\s+$/g,"")}
function classify(e){var t=e.title.toLowerCase();if(/rosh hashanah|yom kippur|sukkot|simchat torah|chanukah|hanukkah|purim|passover|pesach|shavuot|lag b.?omer|tu b.?shvat|high holiday/.test(t))return["holiday","Holiday"];if(/youth|teen|children|child|kids|family|cteen|hebrew school|early childhood|mommy|toddler|camp|bar mitzvah|bat mitzvah/.test(t))return["youth","Youth & Family"];if(/class|learning|learn|torah|talmud|chassidus|kabbalah|jewish study|lecture|course|parsha|lox.*learn/.test(t))return["class","Class"];return["special","Special Event"]}
function prep(a){var c={},i,n,k;for(i=0;i<a.length;i++){n=norm(a[i].title);c[n]=(c[n]||0)+1}for(i=0;i<a.length;i++){n=norm(a[i].title);k=classify(a[i]);a[i].category=k[0];a[i].label=k[1];a[i].recurring=c[n]>1||/\bweekly\b|\bevery\s+(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i.test(a[i].title)}return a}
function meta(icon,text){var x=el("span","ce-mi"),i=el("span","ce-ico",icon);i.setAttribute("aria-hidden","true");x.appendChild(i);x.appendChild(document.createTextNode(text));return x}
function pad(n){n=parseInt(n,10);return n<10?"0"+n:String(n)}
function mon(m){return{january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12}[String(m).toLowerCase()]||0}
function clock(v){var m=tx(v).match(/(\d{1,2}):(\d{2})\s*(am|pm)/i),h;if(!m)return null;h=parseInt(m[1],10);if(m[3].toLowerCase()=="pm"&&h!=12)h+=12;if(m[3].toLowerCase()=="am"&&h==12)h=0;return{h:h,m:parseInt(m[2],10)}}
function times(e){var p=String(e.time||"").split(/\s*-\s*/),a=clock(p[0]),b=clock(p[1]);if(!a)return null;if(!b)b={h:a.h+1,m:a.m};return{a:a,b:b}}
function stamp(d,c){return d.year+pad(mon(d.month))+pad(d.day)+"T"+pad(c.h)+pad(c.m)+"00"}
function gcal(e){var t=times(e),z,desc="";if(!t)return"";z=stamp(e.date,t.a)+"/"+stamp(e.date,t.b);if(e.detailsUrl)desc="More information: "+e.detailsUrl;return"https://calendar.google.com/calendar/render?action=TEMPLATE&text="+encodeURIComponent(e.title)+"&dates="+encodeURIComponent(z)+"&ctz=America%2FNew_York&location="+encodeURIComponent(e.location.text||"")+"&details="+encodeURIComponent(desc)}
function android(e){var t=times(e),m,s,en,fb,desc="";if(!t)return gcal(e);m=mon(e.date.month)-1;s=new Date(+e.date.year,m,+e.date.day,t.a.h,t.a.m).getTime();en=new Date(+e.date.year,m,+e.date.day,t.b.h,t.b.m).getTime();if(e.detailsUrl)desc="More information: "+e.detailsUrl;fb=gcal(e);return"intent://com.android.calendar/events#Intent;scheme=content;action=android.intent.action.INSERT;type=vnd.android.cursor.dir/event;l.beginTime="+s+";l.endTime="+en+";S.title="+encodeURIComponent(e.title)+";S.eventLocation="+encodeURIComponent(e.location.text||"")+";S.description="+encodeURIComponent(desc)+";S.browser_fallback_url="+encodeURIComponent(fb)+";end"}
function esc(v){return String(v||"").replace(/\\/g,"\\\\").replace(/\r?\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function apple(e){var t=times(e),d="",ics;if(!t)return"";if(e.detailsUrl)d="More information: "+e.detailsUrl;ics="BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Chabad of Fort Lee//Events//EN\r\nBEGIN:VEVENT\r\nUID:"+Date.now()+"-"+Math.random().toString(36).slice(2)+"@chabadfortlee.com\r\nDTSTART;TZID=America/New_York:"+stamp(e.date,t.a)+"\r\nDTEND;TZID=America/New_York:"+stamp(e.date,t.b)+"\r\nSUMMARY:"+esc(e.title)+"\r\nLOCATION:"+esc(e.location.text)+"\r\nDESCRIPTION:"+esc(d)+"\r\nEND:VEVENT\r\nEND:VCALENDAR";return"data:text/calendar;charset=utf-8,"+encodeURIComponent(ics)}
function isApple(){return/iPhone|iPad|iPod|Macintosh/i.test(navigator.userAgent)}
function mapUrl(l){var q=encodeURIComponent((l.name?l.name+" ":"")+(l.address||l.text||""));if(/Android/i.test(navigator.userAgent))return"geo:0,0?q="+q;if(isApple())return"https://maps.apple.com/?q="+q;return"https://www.google.com/maps/search/?api=1&query="+q}
function card(e){var c=el("article","ce-c"),d=el("div","ce-d"),main=el("div","ce-main"),mt=el("div","ce-meta"),act=el("div","ce-a"),b,p,a,u;d.appendChild(el("span","ce-m",e.date.month.slice(0,3)));d.appendChild(el("span","ce-day",e.date.day));d.appendChild(el("span","ce-w",e.date.weekday));main.appendChild(el("span","ce-tag",e.label));main.appendChild(el("h2","ce-title",e.title));mt.appendChild(meta("◆",e.date.full));if(e.time)mt.appendChild(meta("●",e.time));main.appendChild(mt);if(e.location.text){p=el("p","ce-loc");p.appendChild(document.createTextNode("Location: "));if(e.location.url){a=el("a","",e.location.name||e.location.text);a.href=mapUrl(e.location);a.target="_blank";a.rel="noopener noreferrer";p.appendChild(a);if(e.location.address){p.appendChild(document.createElement("br"));p.appendChild(document.createTextNode(e.location.address))}}else p.appendChild(document.createTextNode(e.location.text));main.appendChild(p)}if(e.detailsUrl){b=el("a","ce-b","View Details");b.href=e.detailsUrl;act.appendChild(b)}u=/Android/i.test(navigator.userAgent)?android(e):gcal(e);if(u){b=el("a","ce-b ce-cal","Add to Calendar");b.href=u;b.rel="noopener noreferrer";if(!/Android/i.test(navigator.userAgent))b.target="_blank";act.appendChild(b)}if(isApple()){u=apple(e);if(u){b=el("a","ce-b ce-apple"," Apple Calendar");b.href=u;b.setAttribute("type","text/calendar");act.appendChild(b)}}c.appendChild(d);c.appendChild(main);if(act.childNodes.length)c.appendChild(act);c.setAttribute("data-cat",e.category);c.setAttribute("data-rec",e.recurring?"1":"0");c.setAttribute("data-search",tx(e.title+" "+e.date.full+" "+e.time+" "+e.location.text).toLowerCase());return c}
function count(n){var e=$("#ce-count");if(e)e.innerHTML=n+" of "+all.length+" events"}
function status(s){var e=$("#ce-status");if(!e)return;if(s){e.style.display="block";e.innerHTML="";e.appendChild(document.createTextNode(s))}else e.style.display="none"}
function render(a){var l=$("#ce-list"),i;l.innerHTML="";if(!a.length){status("There are no upcoming events listed right now.");count(0);return}for(i=0;i<a.length;i++)l.appendChild(card(a[i]));filter()}
function filter(){var q=tx($("#ce-search").value).toLowerCase(),cs=$$(".ce-c"),n=0,i,s,cat,r,ok;for(i=0;i<cs.length;i++){s=cs[i].getAttribute("data-search")||"";cat=cs[i].getAttribute("data-cat")||"special";r=cs[i].getAttribute("data-rec")=="1";ok=(!q||s.indexOf(q)>=0)&&(active=="all"||cat==active);cs[i].style.display=ok?"":"none";if(ok)n++}count(n);status(n||!all.length?"":"No upcoming events match the selected filters.")}
function getCache(){try{var x=sessionStorage.getItem(CACHE_KEY),o=x?JSON.parse(x):null;return o&&Date.now()-o.time<CACHE_MS?o.html:""}catch(e){return""}}
function setCache(h){try{sessionStorage.setItem(CACHE_KEY,JSON.stringify({time:Date.now(),html:h}))}catch(e){}}
function parsePage(h){var d=new DOMParser().parseFromString(h,"text/html"),it=d.querySelectorAll(".category_item"),a=[],e,i;if(!it.length)throw Error("No events found");for(i=0;i<it.length;i++){e=parse(it[i]);if(e)a.push(e)}return prep(a)}
function init(){var f=$(".ce-f");$("#ce-search").addEventListener("input",filter);f.addEventListener("click",function(ev){var b=ev.target;while(b&&b!==f&&!b.getAttribute("data-f"))b=b.parentNode;if(!b||b===f)return;ev.preventDefault();active=b.getAttribute("data-f");var bs=$$("button",f),i;for(i=0;i<bs.length;i++)bs[i].className="";b.className="on";filter()},true);var cached=getCache();if(cached){try{all=parsePage(cached);render(all)}catch(e){cached=""}}fetch(src,{credentials:"same-origin",cache:"default"}).then(function(r){if(!r.ok)throw Error(r.status);return r.text()}).then(function(h){setCache(h);all=parsePage(h);render(all)}).catch(function(e){if(!cached){if(console&&console.error)console.error(e);status("We were unable to load the upcoming events. Please refresh the page.")}})}
if(document.readyState=="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();